backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
collections:

  - name: "Home" 
    label: "Home"
    folder: "content/english"
    create: false
    fields:
      - { label: "Home", name: "title", widget: "string" }
      - { label: "Header Image", name: "header_image", widget: "image" }
      - { label: "Header Heading", name: "header_heading", widget: "string" }
      - { label: "Header Content", name: "header_content", widget: "markdown" }
     
  
   
  
  
  